services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    working_dir: /usr/app
    command: dotnet watch run
    volumes:
      - ./api:/usr/app
      - ./api/logs:/logs
    networks:
      - s3-upload-network
    ports:
      - 5099:5099
    environment:
      DOTNET_CLIENT_ID: ${DOTNET_CLIENT_ID}
      DOTNET_CLIENT_SECRET: ${DOTNET_CLIENT_SECRET}
      DOTNET_CALLBACK_PATH: ${DOTNET_CALLBACK_PATH}
      DOTNET_CLIENT_URL: ${DOTNET_CLIENT_URL}
      DOTNET_MINIO_SERVICE_URL: ${DOTNET_MINIO_SERVICE_URL}
      DOTNET_MINIO_BUCKET_NAME: ${DOTNET_MINIO_BUCKET_NAME}
      DOTNET_MINIO_ACCESS_KEY: ${DOTNET_MINIO_ACCESS_KEY}
      DOTNET_MINIO_SECRET_KEY: ${DOTNET_MINIO_SECRET_KEY}
  client:
    image: node:lts-alpine3.17
    working_dir: /usr/app
    command: npm start
    volumes:
      - ./client:/usr/app
    networks:
      - s3-upload-network
    ports:
      - 3000:3000
  minio:
    image: quay.io/minio/minio
    volumes:
      - minio:/data
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - s3-upload-network


networks:
  s3-upload-network: {}

volumes:
  minio: {}
